---
title: "Checkpoint 2 - Nível do PSA"
author: "Leonardo Alves dos Santos"
date: "March 30, 2016"
output: html_document
---

```{r, message=FALSE, warning=FALSE}
#Libraries
library(plyr)
library(dplyr)
library(ggplot2)
library(caret)
```

```{r}
#http://statweb.stanford.edu/~tibs/ElemStatLearn/datasets/prostate.data
prostate.data <- read.delim("./data/prostate.data.txt")
```

```{r}
boxplot_age <- ggplot(prostate.data, aes(y=age, x = ""))
boxplot_age +geom_point()
boxplot_age+geom_boxplot(outlier.colour = 'green')
```

```{r}
plt_agexlpsa <- ggplot(prostate.data, aes(lpsa, age))
plt_agexlpsa+geom_boxplot()
plt_agexlpsa+geom_point(colour = "red", size = 2)
```

```{r}
dados_treino <- prostate.data[prostate.data$train==TRUE,]
dados_treino$train <- NULL

dados_teste <- prostate.data[prostate.data$train==FALSE,] 
dados_teste$train<- NULL
```

```{r}
reg_multipla = lm(dados_treino$lpsa ~ dados_treino$lcavol + 
                    dados_treino$lweight + dados_treino$age + dados_treino$lbph + 
                    dados_treino$svi + dados_treino$lcp + dados_treino$gleason + 
                    dados_treino$pgg45)
summary(reg_multipla)
```

```{r}
reg_multipla = lm(dados_treino$lpsa ~ dados_treino$lcavol + 
                                      dados_treino$lweight +
                                      dados_treino$age +
                                      dados_treino$lbph + 
                                      dados_treino$svi + 
                                      dados_treino$lcp +  
                                      dados_treino$pgg45)


summary(reg_multipla)
```


```{r}
predicoes = predict.lm(reg_multipla, dados_treino)
residuos = dados_treino$lpsa - predicoes
axisRange = extendrange(c(dados_treino$lpsa,predicoes)) 
plot(dados_treino$lpsa,predicoes)
abline(0,1,col="blue",lty=2,lwd=2)
```

```{r}
plot(predicoes,residuos)
abline(h=0,col="blue",lty=2,lwd=2)
```

```{r}
qqnorm(residuos)
qqline(residuos, col = 2,lwd=2,lty=2)
```
```{r}
RMSE(predicoes,dados_treino$lpsa)
```


